export const GAME_WIDTH = 1200;
export const GAME_HEIGHT = 600;

export const FIELD = {
  WIDTH: 1100,
  HEIGHT: 500,
  OFFSET_X: 50,
  OFFSET_Y: 50,
  ENDZONE_WIDTH: 150,
  LINE_COLOR: 0xffffff,
  GRASS_COLOR: 0x2e8b57,
  ENDZONE_LEFT_COLOR: 0x1a5c3a,
  ENDZONE_RIGHT_COLOR: 0x1a3c5a,
};

export const FIELD_BOUNDS = {
  LEFT: FIELD.OFFSET_X,
  RIGHT: FIELD.OFFSET_X + FIELD.WIDTH,
  TOP: FIELD.OFFSET_Y,
  BOTTOM: FIELD.OFFSET_Y + FIELD.HEIGHT,
  ENDZONE_LEFT_END: FIELD.OFFSET_X + FIELD.ENDZONE_WIDTH,
  ENDZONE_RIGHT_START: FIELD.OFFSET_X + FIELD.WIDTH - FIELD.ENDZONE_WIDTH,
};

export const PLAYER = {
  RADIUS: 12,
  MAX_SPEED: 200,
  ACCELERATION: 600,
  DRAG: 400,
  CATCH_RADIUS: 30,
  MARK_RADIUS: 50,
  TEAM_A_COLOR: 0x3366ff,
  TEAM_B_COLOR: 0xff3333,
  CONTROLLED_OUTLINE: 0xffff00,
};

export const DISC = {
  RADIUS: 6,
  COLOR: 0xffffff,
  MAX_POWER: 500,
  MIN_POWER: 100,
  CHARGE_RATE: 400,
  DRAG_FACTOR: 0.997,
  GRAVITY: 15,
  GROUND_THRESHOLD: 0.5,
};

export const STALL = {
  MAX_COUNT: 10,
  INTERVAL_MS: 1000,
};

export const GAME_STATES = {
  BOOT: 'BOOT',
  MENU: 'MENU',
  KICKOFF_PULL: 'KICKOFF_PULL',
  LIVE_PLAY: 'LIVE_PLAY',
  STALL_COUNT: 'STALL_COUNT',
  TURNOVER: 'TURNOVER',
  SCORE: 'SCORE',
  RESET_AFTER_SCORE: 'RESET_AFTER_SCORE',
  GAME_OVER: 'GAME_OVER',
};

export const DISC_STATES = {
  HELD: 'HELD',
  THROWN: 'THROWN',
  GROUND: 'GROUND',
  INTERCEPTED: 'INTERCEPTED',
};

export const TEAMS = {
  A: 'A',
  B: 'B',
};

export const PLAYER_ROLES = {
  HANDLER: 'handler',
  CUTTER: 'cutter',
};

export const SCORE_TO_WIN = 15;

export const AI = {
  DECISION_INTERVAL: 500,
  SPACING_DISTANCE: 80,
  MARK_DISTANCE: 40,
  INTERCEPT_RADIUS: 60,
  THROW_ACCURACY_VARIANCE: 0.15,
  CUT_SPEED_FACTOR: 0.85,
  OPEN_SPACE_THRESHOLD: 100,
};

export const PULL = {
  MIN_POWER: 300,
  MAX_POWER: 500,
  AIM_SPEED: 1.5,
};
